# Generated by Django 3.1.7 on 2021-03-07 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_auto_20210306_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
